#!/bin/bash
#
# Original source: 
# https://zipproth.de/cheat-sheets/hugo-asciidoctor/

echo  "Local Script..."
if [ -f /usr/local/bin/asciidoctor ]; then
  ad="/usr/local/bin/asciidoctor"
else
  ad="/usr/bin/asciidoctor"
fi

   
$ad -v -B . \
  -r asciidoctor-diagram \
  -r asciidoctor-revealjs \
  -a icons=font \
  -a docinfo=shared \
  -a nofooter \
  -a sectanchors \
  -a experimental=true \
  -a figure-caption! \
  -a source-highlighter=rouge \
  -a rouge-style=molokai \
  -a toc-title! \
  -a stem=mathjax \
  --no-header-footer \
  --safe \
  --trace \
  - | sed -E -e "s/img src=\"([^/]+)\"/img src=\"\/diagram\/\1\"/"

mkdir -p static/diagram

if ls *.svg >/dev/null 2>&1; then
  mv -f *.svg static/diagram
fi

if ls *.png >/dev/null 2>&1; then
  mv -f *.png static/diagram
fi
